### ISSUE TITLE
Completed?

### ISSUE THREAD

**Issue by ridasalam** [YuefeiZ/PANet#1]
Hi, is this completed?

**Comment by YuefeiZ** [comment]
yes

**Comment by YuefeiZ** [comment]
Do find any problems?

**Comment by yuskey** [comment]
Is the panet.py file in the pythontest folder the correct python file to run the model?

**Comment by YuefeiZ** [comment]
I use panet.py can get this :
2/1328 [..............................] - ETA: 3:40:01 - loss: 2.7862 - rpn_class_loss: 0.0978 - rpn_bbox_loss: 1.3201 - mrcnn_class_loss: 0.0811 - mrcnn_bbox_loss: 1.0492 - mrcnn_mask_loss: 0.2379        
   3/1328 [..............................] - ETA: 2:31:54 - loss: 3.4623 - rpn_class_loss: 0.0926 - rpn_bbox_loss: 2.4519 - mrcnn_class_loss: 0.0597 - mrcnn_bbox_loss: 0.6995 - mrcnn_mask_loss: 0.1586

**Comment by YuefeiZ** [comment]
using  the panet.py, I can get this :
2/1328 [..............................] - ETA: 3:40:01 - loss: 2.7862 - rpn_class_loss: 0.0978 - rpn_bbox_loss: 1.3201 - mrcnn_class_loss: 0.0811 - mrcnn_bbox_loss: 1.0492 - mrcnn_mask_loss: 0.2379
3/1328 [..............................] - ETA: 2:31:54 - loss: 3.4623 - rpn_class_loss: 0.0926 - rpn_bbox_loss: 2.4519 - mrcnn_class_loss: 0.0597 - mrcnn_bbox_loss: 0.6995 - mrcnn_mask_loss: 0.1586

**Comment by YuefeiZ** [comment]
It can run the model
